select  
GMV.lead_id,original_order_user_number,
pay_group_period_name,
trade_group_period_name,
channel_name_1,channel_name_2,channel_name_3,flow_pool_name,get_customer_way_name,
order_number,order_status,
pay_success_timestamp,
full_refund_timestamp,
is_pay_success_order,
is_part_refund_order,
is_full_refund_order,original_order_number,original_order_pay_success_timestamp,
latest_order_number,latest_order_full_refund_timestamp,latest_order_is_pay_success_order,latest_order_is_part_refund_order,latest_order_is_full_refund_order,
performance_employee_email_name,performance_city_name,performance_talent_type_name,performance_first_level_department_name,performance_second_level_department_name,performance_third_level_department_name,performance_department_path_json,
clazz_biz_number,clazz_type,clazz_begin_timestamp,clazz_end_timestamp,main_teacher_number,main_teacher_email_name,course_first_level_department_name,course_second_level_department_name,course_third_level_department_name,course_first_level_subject_name,course_second_level_subject_name,course_third_level_subject_name,
course_name,course_category_code,school_department_name,grade_name,school_year,school_term_name,
is_renew_class_amount,is_renew_class_user,school_subject_name,mapping_school_subject_name,is_blacklist_user,put_plan_name,
trade_timestamp,pay_refund_type,
income_amount/100 income_amount,
refund_amount/100 refund_amount,
(income_amount-refund_amount)/100 promit_amount,
lead_period_name,trade_period_name,trade_period_conversion_begin_time,trade_period_conversion_end_time,trade_period_mapping_first_level_department_name,trade_period_mapping_second_level_department_name,pay_period_name,pay_period_conversion_begin_time,pay_period_conversion_end_time,pay_period_mapping_first_level_department_name,pay_period_mapping_second_level_department_name,pay_period_first_level_course_project_name,pay_period_second_level_course_project_name,is_same_trade_lead_period,virtual_direct_leader_email_name,rule_name
FROM
(
select * from service_dw.dws_crm_order_lead_attribute_income_refund_stats_detail_hf
where  dt=format_datetime(NOW()-interval '2' hour,'YYYYMMdd') and hour=format_datetime(NOW()-interval '2' hour,'HH')
) gmv
left JOIN
(
select distinct lead_id,put_plan_name,employee_email_name,channel_name_1,channel_name_2,channel_name_3,flow_pool_name,get_customer_way_name,rule_name,virtual_direct_leader_email_name from
bdg_ba.dm_crm_lead_cost_gmv_communication_learn_full_link_df  where  dt=format_datetime(NOW()-interval '2' hour,'YYYYMMdd') and hour=format_datetime(NOW()-interval '2' hour,'HH')
) ld on gmv.lead_id=ld.lead_id and ld.employee_email_name=gmv.performance_employee_email_name
where 
performance_second_level_department_name='青橙项目部'
and trade_timestamp>${begin_trade_time}
and trade_timestamp<${end_trade_time}
